name: "Autobump version and publish"
description: "Hedia's npm packages autobumper & publisher"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token required to publish packages"
    required: true
  NPM_TOKEN:
    description: "NPM token required to npm install"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Login to github registry"
      run: echo inputs.GITHUB_TOKEN | docker login ghcr.io --username ${{ github.actor }} --password-stdin
    - name: "Build docker image"
      run: docker build -t ${{github.event.repository.name}} --build-arg NPM_TOKEN=${{inputs.NPM_TOKEN}} .
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: "Tag build"
      run: docker tag ${{github.event.repository.name}} ghcr.io/hedia-team/${{github.event.repository.name}}:${{package-version.outputs.current-version}}
    - name: "Push build"
      run: docker push ghcr.io/hedia-team/${{github.event.repository.name}}:${{package-version.outputs.current-version}}
